version: '3.2'
services:
  catalogos:
    image: "hlp_catalogos:1808060959.1.0-dev"
    ports:
     - "8091:8091"
    environment:
      - DB_USER_NAME=postgres
      - DB_USER_PASSWORD=desa2018rrollo
      - DB_URL=192.168.70.167
      - DB_PORT=5432
      - DB_NAME=dbpegasus
    networks:
        default:
            ipv4_address: 172.19.1.1
  tickets:
    image: "hlp_tickets:1808040054.1.0-dev"
    ports:
     - "8092:8092"
    environment:
      - DB_USER_NAME=postgres
      - DB_USER_PASSWORD=desa2018rrollo
      - DB_URL=192.168.70.167
      - DB_PORT=5432
      - DB_NAME=dbpegasus
    networks:
        default:
            ipv4_address: 172.19.1.2
  notificaciones:
    image: "hlp_notificaciones:1808031803.1.0-dev"
    ports:
     - "8093:8093"
    networks:
        default:
            ipv4_address: 172.19.1.3

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/16
